### ISSUE TITLE
Randomly Missing Content

### ISSUE THREAD

**Issue by rr1000** [contentful/contentful_middleman#100]
Hello. I'm building a new (fairly large) site with Contenful and Middleman. I currently have 13 content types:

```ruby
    f.content_types = {
        academy: 'academy',
        blog: 'blog',
        cta: 'cta',
        caseStudy: 'caseStudy',
        customers: 'customers',
        glossary: 'glossary',
        person: 'person',
        podcastEntry: 'podcastEntry',
        pressReleases: 'pressReleases',
        products: 'products',
        quotes: 'quotes',
        tags: 'tags',
        whitepapers: 'whitepapers'
    }
```

I'm using my preview API. At times when I pull in content using `bundle exec middleman contentful` only a select few directories are pulled in. This results in my proxy blocks not working. To fix this issue I added simple checks. Ex:

```ruby
    if Dir.exist?(config.data_dir + "/site/pressReleases")
        data.site.pressReleases.each do |id, pressRelease|
            proxy "/press-release/#{pressRelease[:slug]}.html", "/contentful_templates/press_release.html", :locals => { :item => pressRelease }, :ignore => true
        end
    else
        puts "\n\n\npressReleases doesn't exist!\n\n"
    end
```

There are certain directories (such as `pressReleases`) that consistently are not pulled in. At other times random directories will also not be pulled in. The inconsistent nature of this issue leads me to believe it's a bug. Any help is greatly appreciated.

Some other information that might be relevant. I'm using the `dl/upgrade-to-v4` branch with middleman v `4.1.13`.

**Comment by rr1000** [comment]
I also created a new middleman project with middleman `3.4.1` to confirm that the issue wasn't specific to `v4`. I'm seeing the same lack of content on `3.4.1` and the production `contentful_middleman` gem that I did on `dl/upgrade-to-v4` with `4.1.13`.

**Comment by dlitvakb** [comment]
Hey @rr1000,

Could you paste your `activate` block? (please remove credentials)

Also, what's the amount of entries you have in your space? If you have over 100, the issue is most likely that you're not pulling all of your entries. There are 2 ways to solve this issue, if you have less than 1000 entries, you can add `limit: 1000` to your `cda_query`. If you have over 1000 entries, set `f.all_entries = true` in your activate block.

Cheers

**Comment by rr1000** [comment]
@dlitvakb That worked prefect! Thank you so much. Cheers!

**Comment by allanwhite** [comment]
Really appreciate the quick response @dlitvakb, it's great tech. Best wishes!

**Comment by dlitvakb** [comment]
No problem! Cheers
