### ISSUE TITLE
Netlify Build Errors for `middleman-core` and `thor`

### ISSUE THREAD

**Issue by claudiovallejo** [contentful/contentful_middleman#101]
Hello,

I finished integrating a Middleman Project with Contentful and have been able to build the site locally. The problem I'm running into, though, is when building the site with Netlify. Netlify's build log prints the following:

```
11:27:17 AM: Gem bundle installed
11:27:18 AM: /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/data.rb:163:in `method_missing': undefined method `site' for #<Middleman::CoreExtensions::Data::DataStore:0x0000000320a820> (NoMethodError)
from /opt/build/repo/config.rb:66:in `initialize'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/data.rb:31:in `initialize'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:213:in `initialize'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `new'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `inst'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/build.rb:95:in `shared_instance'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/cli/build.rb:62:in `build'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /opt/build/cache/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
from /opt/build/cache/bundle/ruby/2.1.0/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
from /opt/build/cache/binstubs/middleman:17:in `load'
from /opt/build/cache/binstubs/middleman:17:in `<main>'
11:27:18 AM: Cached ruby gems
11:27:19 AM: Cleaning up docker container
11:27:19 AM: Error running command: Build script returned non-zero exit code: 1
11:27:19 AM: Error running command: Build script returned non-zero exit code: 1
11:27:20 AM: Finished processing build request
```

I'm currently running Ruby 2.3.0p0 and Middleman 3.4.1 and you can find the project's repo [here]((https://github.com/tymforest/sitio)).

Any tips/help would be appreciated.

**Comment by dlitvakb** [comment]
Hey @claudiovallejo,

Looks like you're doing somewhere in your code `data.site. ...` and the `site` key is not being recognized.

This can happen due to 2 different things:

1) Your data has not been pulled yet (either by running `middleman contentful` or other script that generates data)
2) You don't have any subfolder within your data folder called site (probably because the space alias in the contentful activation is different than site).

Hope that helps.

Cheers

**Comment by claudiovallejo** [comment]
Hi @dlitvakb, thank you for your help. Your suggestions helped me realize I was missing several steps to correctly integrate my Middleman project with Contentful.

Just for reference, the steps I was missing were the following:
- Missing `bundle exec middleman contentful && bundle exec middleman build` in Netlify Build Command to pull the latest content changes prior to building Middleman project.
- My `.gitignore` was ignoring `/data`, which prevents Netlify from pulling the most up-to-date content from Contentful
- Created a Webhook with Contentful and integrated with Netlify and Middleman.

Also, I found this article on Contentful's blog which helped me understand what steps I was missing -> (Dynamic Product Management in a Static E-commerce Workflow)[https://www.contentful.com/blog/2016/02/10/snipcart-middleman-contentful/]
