### ISSUE TITLE
Remove unpublished entries?

### ISSUE THREAD

**Issue by mrh-is** [contentful/contentful_middleman#106]
This extension does not remove entries that have been archived or deleted. That would be pretty useful.

Though from what I know of how this works, I'm not sure it would be possible to write this in a "smart"/efficient way. There's no way to get deleted entries AFAIK, and even archived entries would require another API call. I suppose you could somehow start with a list of all the files in the output location(s), then remove the ones that match the API.

In any event, if this cannot be accomplished through this extension, do you have recommendations on how to do this (hopefully other than "do it all manually" 😝)?

[Sorry if this has already been brought up; I couldn't find it in the issues if so.]

**Comment by dlitvakb** [comment]
Hey @mrh-is,

Sadly the answer is "do it all manually".

Reason behind it, is that the tool cannot differentiate between unpublished entries and entries that are published but not reached by `includes`, therefore there's no way to know exactly which is which and remove it from the response.

The API keeps the references even if they are unpublished/archived for consistency reasons (else every object in a space would have to be checked and updated, and in spaces with over 100k entries, this is extremely costly), it's the job of the publisher to remove any reference that is no longer valid.

Cheers

**Comment by dlitvakb** [comment]
The SDK now automtically filters out unpublished/deleted entries, therefore this is now done automatically when doing the exports.

Cheers

**Comment by phuriphatpetdee** [comment]
@dlitvakb, so is it mean that we can't search for unpublished entries?
