### ISSUE TITLE
space-hash causing build to fail

### ISSUE THREAD

**Issue by joshRpowell** [contentful/contentful_middleman#111]
using the [experimental branch](https://github.com/contentful/contentful_middleman/tree/dl/upgrade-to-v4)
 
running `middleman contentful --rebuild` with `.[app]-site-hash` present in root i get the following error:
![with site-hash](https://cloud.githubusercontent.com/assets/6732638/23219164/56bd10e0-f8ec-11e6-9c9e-6185cdca3b68.png)

deleting the `.[app]-site-hash` from root allows the build to run without issue:
![without site-hash](https://cloud.githubusercontent.com/assets/6732638/23219445/10d22e8e-f8ed-11e6-848b-cabcf195e293.png)

any thoughts as to why the site-hash file would interfere with my webpack build? 

here is my config.rb:

```ruby
activate :directory_indexes
activate :autoprefixer

# Per-page layout changes:
#
# With no layout
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

set :relative_links, true
set :relative_paths, true
set :css_dir, 'assets/stylesheets'
set :js_dir, 'assets/javascripts'
set :images_dir, 'assets/images'
set :fonts_dir, 'assets/fonts'
set :layout, 'layouts/app'
set :partials_dir, 'layouts/partials'

# Reload the browser automatically whenever files change
configure :development do
  activate :livereload
end


###########################
## Helpers
###########################
helpers do

  def render_partial( partial_name )
    partial "layouts/partials/#{partial_name}"
  end

end


activate :contentful do |f|
  f.access_token  = ENV['ACCESS_TOKEN']
  f.space         = { annuity_support: ENV['SPACE'] }
  f.content_types = { resource: 'resource' }
end


# Build-specific configuration
configure :build do
  activate :favicon_maker do |f|
    f.icons = {
      'favicon.png' => [
        { icon: 'favicon.png', size: '16x16' },
        { icon: 'favicon.ico', size: '64x64,32x32,24x24,16x16' }
      ]
    }
  end

  activate :relative_assets
  activate :gzip
  activate :minify_css
  activate :minify_html
  activate :minify_javascript
  activate :asset_hash
  activate :meta_tags
end

activate :deploy do |deploy|
  deploy.build_before = true
  deploy.deploy_method = :git
end

activate :external_pipeline,
         name: :webpack,
         command: build? ?
          './node_modules/webpack/bin/webpack.js --bail -p' :
          './node_modules/webpack/bin/webpack.js --watch -d --progress --color',
         source: '.tmp/dist',
         latency: 1
```

**Comment by dlitvakb** [comment]
Hey @joshRpowell,

As promised, a `DEPLOYING` file has been added to document platform specific issues.

It's currently being reviewed and will be merged ASAP.

https://github.com/contentful/contentful_middleman/pull/112

Cheers

**Comment by dlitvakb** [comment]
This has been merged.

Cheers

**Comment by crtvhd** [comment]
@dlitvakb I don't really see how #112 was related to this issue. I'm having the same issue: Apparently `external_pipeline` gets triggered when running `bundle exec middleman contentful`.

**Comment by dlitvakb** [comment]
Hey @crtvhd,

You should add the `.*-site-hash` to your `.gitignore`.

The idea of the `DEPLOYING` file, is to give users a chance to share deployment platform specific solutions, e.g. "When deploying on Netlify, do such and such to avoid seeing X". It "solves", this issue because this was a platform specific problem that @joshRpowell got to fix, and that's why this document was provided.

The document as of now is currently empty, but I'd love for @joshRpowell to share his solution.

Cheers

**Comment by joshRpowell** [comment]
@crtvhd I have a PR open for Netlify the `DEPLOYING` file. 

when I need to update Contentful data I have to remove the `site-hash`
```
rm -r .*-space-hash
```
then run
```
middleman contentful --rebuild
```
