### ISSUE TITLE
Infinite loops via base mapper

### ISSUE THREAD

**Issue by knupska** [contentful/contentful_middleman#113]
The change made to `lib/contentful_middleman/mappers/base.rb` in 031fd8bf30649e98dd083bdf3a962a30555ba8d5 has introduced the possibility of infinite loops.

With the behaviour prior to the change, when an item that was previously `:discovered` was going to be mapped, it would only output the `id` of the item.

The change seems to have been implemented to ensure that subsequent references also output.

Unfortunately by always adding the item to the queue (regardless of if it has been discovered previously) it suddenly makes any cyclical references in Contentful trigger an infinite loop in the mapper, and it also seems to have left the `:discovered` logic orphaned (whereby `ids` are added to that array but never actually referenced by any useful logic, other than to check if other `ids` should be added to the array).

A best of both worlds approach would require an item being mapped to have an awareness of the `ids` of ancestors, so that it only gets mapped when the `id` does not exist in that ancestor chain (rather than simply being something that had been `:discovered` previously).

**Comment by dlitvakb** [comment]
Hey @knupska,

Could you recreate this issue within a space and share it, so I can investigate the issue further? As I haven't faced this issue myself yet.

Cheers
