### ISSUE TITLE
Missing locale for assets

### ISSUE THREAD

**Issue by andrezimpel** [contentful/contentful_middleman#114]
My contentful space currently got two languages, english and german. I am defining locale: '*' in my cda query and I get all available fields for the entries. I only get de default language for assets tho. Is there any trick or am I something missing to get both locals for assets too?

```ruby
activate :contentful do |f|
  f.space         = { zuckerjagdwurst: '###' }
  f.access_token  = '###'
  f.cda_query     = { include: 1, locale: '*' }
  f.content_types = { posts: 'posts', authors: 'authors', series: 'series', categories: 'categories', recipes: 'recipes' }
end
```

```yaml
---
:id: 1MahpLrjhmOc2oic8OaES6
:name:
  :de: name german
  :en: name english
:slug:
  :de: slug-german
  :en: slug-english
:image:
  :de:
    :title: german title
    :description: german description
    :url: "//images.contentful.com/bt3fcszqk4za/bVDt1RFEQ0eUUQyOWU8Uu/534a17eff1f9bd39e4668def25a9d332/exploring-kanye-yeezy-sites-20.jpg"
```

**Comment by dlitvakb** [comment]
Hey @andrezimpel,

Which version of the gem are you using?

Cheers

**Comment by andrezimpel** [comment]
hi @dlitvakb 

I'm running `contentful_middleman (1.5.0)`

Thanks!

**Comment by dlitvakb** [comment]
If your image also defined for the `en` locale?

**Comment by andrezimpel** [comment]
Yea, I got en and de. There aren't no empty fields also. For entries everything works perfect tho!

**Comment by dlitvakb** [comment]
Can you open a support request and send your access token and space id? I'd need to look into your specific issue.

Cheers

**Comment by andrezimpel** [comment]
Yea, shall I drop you any info so you can find it easily?

**Comment by dlitvakb** [comment]
Just ask for me and provide your complete `activate :contentful` block, and support will assign the ticket to me.

Cheers

**Comment by dlitvakb** [comment]
Closing this issue as it's been takled through support channels.

Cheers
