### ISSUE TITLE
Using `type` as the Field ID will result in no data being outputted for that Content Type when building the YAML files

### ISSUE THREAD

**Issue by j0b0sapi3n** [contentful/contentful_middleman#116]
I ran into this odd error while trying to figure out why a specific Content Type wasn't being returned anymore when running `middleman contentful`. The Content Type has 10 fields, and only the ID was being returned now. Very strange. I disabled each field one by one until I discovered that if it was a Short Text field that was causing this. More specifically, it was because I named the field ID `type`.  Once I changed the field ID to something like `itemType` it worked.

Why does this happen?

**Comment by dlitvakb** [comment]
This happens due to an issue when there are conflicting names between the `sys` properties and the `fields`. This will be fixed with the update to the `2.0.0` `contentful.rb` SDK, I'll have this done within the next few days. For the moment, you can change your field ID.

Cheers
