### ISSUE TITLE
How can we output the content type in entries? [Question]

### ISSUE THREAD

**Issue by allanwhite** [contentful/contentful_middleman#117]
We use `middleman_contentful` in our middleman app to pull down data from Contentful, and render it as Yaml. Works great. However, as we're trying to implement related entries across content types (aka sections or categories; so a blog entry referencing a podcast entry), it seems the `sys.id` property or `linkContentType` (in linked entries) isn't rendered in the yaml. We have no way of mapping these to our routes (folder slugs) in our app. We played around with include depth and it had no effect on that.

Is there a configuration setting in our middleman `config.rb` that would tell it to include the content type in entries (especially related entries)? This information seems kind of essential to making use of related entries at all. 

```
# Contentful configuration in config.rb
activate :contentful do |f|
    f.space = { site: '[hash]'}
    f.access_token = '[hash]'
    f.use_preview_api = false
    f.all_entries = true
    f.content_types = {
        blog: 'blog',
        podcastEntry: 'podcastEntry'
    }
end
```
Typical YAML blog entry, with related item, only outputs something like this:
```
:relatedEntries:
- :id: [hash]
  :title: 'podcast entry'
  :slug: podcast-name
```
And the JSON schema for the related entries looks like this:
```
...{
      "name": "Related Entries",
      "id": "relatedEntries",
      "type": "Array",
      "items": {
        "type": "Link",
        "linkType": "Entry",
        "validations": [
          {
            "linkContentType": [
              "blog",
              "podcastEntry"
            ]
          }
        ]
      }
```
Seems like it'd include `linkContentType` or something by default. If not, why? Is there a way we can have this returned & rendered into the Yaml files?

**Comment by dlitvakb** [comment]
Hey @allanwhite,

To do this you have to include a Custom Mapper.

It works by creating a class and redefining it's `#map` method.

```ruby
class MapperWithContentTypeData < ContentfulMiddleman::Mapper::Base
  def map(context, entry)
    super
    context.content_type_id = entry.content_type.id
  end
end
```
Then assign it in your `activate` block, you can read more here: https://github.com/contentful/contentful_middleman#custom-mappers

Cheers

**Comment by dlitvakb** [comment]
As an additional note, I'll be adding a `_meta` block for every entry including Content Type, and Created and Updated At dates to the next release, I'll be working on it next week.

Cheers

**Comment by conraddecker** [comment]
@allanwhite I was running into the same issue. [https://github.com/contentful/contentful_middleman/issues/118] does fix this but only for the master branch, it doesn't work for the v4 branch. If it helps, happy to show you what I did for v4. Seems to do the trick for me but I haven't done more than smoke test it so haven't created a PR for it. Sounds like there's some discussion here [https://github.com/contentful/contentful_middleman/issues/56#issuecomment-292562322] about how to proceed with v4 compatibility.

**Comment by allanwhite** [comment]
@conraddecker Conrad, I would love to hear about your experience implementing it on MM v4. I read the discussion on the way forward, certainly I'd rather break things and stay current.

**Comment by conraddecker** [comment]
@allanwhite Sure thing :) It was pretty straight forward but as I mentioned I haven't done much more than smoke test it. It seems to be working for me for now but also sounds like the main v4 branch is going to be keeping parity with master moving forward. 

In the meantime, I followed @dlitvakb 's lead on master, forked the repo, made a minor update and am targeting my specific repo in my project's Gemfile for the time being. A little hacky but got me what I needed to finish up a client project while I waited for the decision to be made on the v4 branch :) 

More than welcome to take a look and take what's helpful: https://github.com/conraddecker/contentful_middleman/commit/88fe39b77798d09579d4bb680768938d1a624f5f

**Comment by dlitvakb** [comment]
Hey @conraddecker, @allanwhite,

The decision has been made and the update will occur this Tuesday, a branch without the update will be created from the current `v4` branch, to keep it as `1.x` stable, and following that the updates that are on `master` will be applied to the current `v4` branch, keeping it in parity with the current `master`. You can follow up on the discussion here: https://github.com/contentful/contentful_middleman/issues/56#issuecomment-294164388

Cheers
