### ISSUE TITLE
Additional entry properties for nested data

### ISSUE THREAD

**Issue by cearls** [contentful/contentful_middleman#119]
I've created a custom mapper and I need to include additional entry properties for nested data. Is there a better way to do this than what I've done for content type id?

```
class PostMapper < ContentfulMiddleman::Mapper::Base
  def map(context, entry)
    #super
    @children = {
      :queue => [{ :context => context, :entry => entry }],
      :discovered => [entry.id] }
    while !@children[:queue].first.nil? do
      nxt = @children[:queue].pop
      context = nxt[:context]
      entry = nxt[:entry]
      context.content_type_id = entry.sys[:contentType].id
      map_entry_full(entry, context)
    end

    context.date = entry.sys[:createdAt].strftime("%Y/%m/%d")
  end
end
```

**Comment by dlitvakb** [comment]
Hey @cearls,

This is now added already in `master` and will be released shortly.

If using Middleman v4, the update to upstream `master` will be done in the `dl/upgrade-to-v4` branch within the next few hours.

Cheers

**Comment by cearls** [comment]
@dlitvakb Thanks!
