### ISSUE TITLE
Using Contentful Preview API with Middleman

### ISSUE THREAD

**Issue by macandcheese** [contentful/contentful_middleman#120]
Perhaps this is more of a question than an issue - I'm struggling to find a way to allow editors to preview draft or unpublished content through the editor interface in a hosted app.

Obviously with Middleman you need to build the project to populate data in the templates, so I'm at a bit of a loss as far as how to set up the preview. Even using the "with_preview" helper in docs, that's simply for using locally correct? Is it possible to have a hosted preview using Middleman?

Even if I set up a "staging" app that mirrors my app but with the preview api, I don't understand how clicking the preview link in editor could possibly pipe in preview data w/out triggering a rebuild somehow.

I'm clearly just missing a piece of the puzzle, hopefully someone can shed light? or possibly other solutions that don't use Middleman for the preview piece?

**Comment by dlitvakb** [comment]
Hey @macandcheese,

You can set the `use_preview_api` configuration flag to `true`, that will use the Preview API instead of the Delivery API for generating your serialized files, then you can deploy it as a regular site. Just keep it in a safe place so no unpublished content leaks to the public.

Cheers

**Comment by macandcheese** [comment]
Hi @dlitvakb - thanks for the response. Perhaps this is more feedback for Contentful UI vs. Middleman gem. Here's the setup:

I'll have a staging environment (stating.site.com - basically a mirror codebase of my live site), where I'll deploy anything changed to draft status in the editor UI, via webhook. However, the build and deployment of that draft will take around 5 minutes from clicking "draft" to being able to preview the content item on the staging site. During that 5 minutes, the Contentful editor UI will show the "preview" button that's configured for a URL that hasn't been published yet, which is kind of confusing for editors.

Is there a way to customize the "Preview" button in the editor UI?

**Comment by dlitvakb** [comment]
Hey @macandcheese,

In the WebApp, go to your desired Space, then click on `Settings` -> `Content preview`.
There you can customize the behavior of the `Preview` button to point to your staging site.

Hope that helps,

Cheers
