### ISSUE TITLE
Localised Assets

### ISSUE THREAD

**Issue by fkamras** [contentful/contentful_middleman#126]
Is there a way I get the localised title and description of the asset when pulling data from contentful?

Thanks!

**Comment by dlitvakb** [comment]
Hey @fkamras,

If you're using either `locale: 'some-specific-locale'` or `locale: '*'` as part of your `cda_query`, then locales should be automatically handled.

Cheers

**Comment by fkamras** [comment]
Hey @dlitvakb 
I'm using this in my config file

`f.cda_query     = { limit: 1000, include: 2, locale: '*' }`

But the returned data only contains the english title and description even though different descriptions and titles are added for 3 more locales.

**Comment by dlitvakb** [comment]
Do you have your asset localized as well? Or are you using diferent references for each locale?

**Comment by fkamras** [comment]
The asset is localised (by default I guess). The field that references the asset is not.

**Comment by dlitvakb** [comment]
Thanks the issue then, either have the field + asset localized, as in the gem locales are "pass-through" so if you're using a specific locale for a field, it will try to fetch the same locale in the referenced asset. Or use, localized field + non-localized asset per locale. Whichever fits your content best, but both should work.

Hope this helps

Cheers

**Comment by dlitvakb** [comment]
Another solution, is to use a custom mapper, so that assets get every locale serialized, disregarding what the desired locale is, and use that instead.

This will complicate the accessor code a bit, and also have you re-implement the mapper. But if it's a tradeoff you're willing to do, it's something that's possible.

Cheers

**Comment by fkamras** [comment]
Thanks!
I went with the first option. It feels a bit redundant linking the same image to all the fields, but it worked.

**Comment by dlitvakb** [comment]
Glad it solved your problem!

Cheers
