### ISSUE TITLE
Back reference example outdated?

### ISSUE THREAD

**Issue by islegend** [contentful/contentful_middleman#129]
I am trying to figure out the best way to map back references. I stumbled upon: https://github.com/contentful/contentful_middleman/blob/master/examples/mappers/backref.rb but it seems that the syntax is out dated. Or am I just using it wrong? I am requiring it at the top of config.rb and passing it in as a mapper. 

If it is outdated, is there anyway someone who knows how it works could update it? 

Thanks.

**Comment by dlitvakb** [comment]
Hey @islegend,

You're correct, this is outdated as it's using the `1.x` CDA SDK.

`e.sys[:contentType].id == @@content_type_id` should be changed to `e.sys[:content_type].id == @@content_type_id`. The rest can be kept as is.

I will update the snippet to reflect the current version.

Cheers

**Comment by dlitvakb** [comment]
This has been already done.

Closing.

Cheers
