### ISSUE TITLE
Nested entires and assets are not transformed by localize_value.

### ISSUE THREAD

**Issue by kylorhall** [contentful/contentful_middleman#130]
The helper `localize_value` ignores all nested entries and links and will return only a partially localized value.

I also noticed that localized_entry converts an entry from a `Thor::CoreExt::HashWithIndifferentAccess` to a `Hash`, meaning the localized data is no longer accessible via symbol names (eg. `e[:id]` and `e['id']` before and only `e['id']` after).

Here's a Gist with some cleaned up data dumps: https://gist.github.com/kylorhall/17e156aef927aeefd2698d535be810d9

### Basically, an entry coming through (after mapping) looks like this:
```
  {
    id: 'foo',
    name: { 'en' => 'foo' },
    categories: { 'en' => [{ id: 'foo', _meta: { ... }, name: { 'en' => 'foo' } }] }
  }
```

### After `localize_entry`
(categories.name still has localization):
```
  {
    id: 'foo',
    name: 'foo',
    categories: [{ id: 'foo', _meta: { ... }, name: { 'en' => 'foo' } }]
  }
```

## Background Information
- cda_query `cda_query = { locale: '*' }`
- Ruby 2.3.1
- Middleman 3.4.1
- contentful_middleman 2.1.1

**Comment by dlitvakb** [comment]
Closed via #131.
