### ISSUE TITLE
Contentful info seems to be coming in as snake case vs camel case

### ISSUE THREAD

**Issue by javaporter** [contentful/contentful_middleman#132]
I'm not sure which commit caused this (sorry, I know that's not super helpful), but at some point, content with a space in the name started coming in as snake_case, when it used to be camelCase. So, even though [my Contentful ID is 'eventTitle'](https://www.dropbox.com/s/1293c2ij29prsqc/Screenshot%202017-08-17%2018.50.24.png?dl=0), when I pull it in via `middleman contentful`, it [comes in](https://www.dropbox.com/s/0hcoxq5lms496lw/Screenshot%202017-08-17%2019.01.42.png?dl=0) as `event_title`. This may not be a contentful_middleman issue, but was my best guess.

**Comment by dlitvakb** [comment]
Hey @javaporter,

That is right, this has been a change introduced in May with release 2.0.0, you can find more info on what changed here: https://github.com/contentful/contentful_middleman/blob/master/CHANGELOG.md#200

If you want the previous behaviour, feel free to stay on the 1.x version.

I personally recommend you to upgrade to 2.x to keep up with the latest updates and improvements.

Cheers

**Comment by javaporter** [comment]
I must have missed that. That'll learn me to bundle update and not read the terminal (actually, probably not, but maybe). Thanks for the fast response.

**Comment by dlitvakb** [comment]
No problem,

Anyway, I'm planning to add an option for disabling snake_case, as there are some users that have isomorphic setups and would like to have them consistent.

I'll let you know when that's done, should be coming out within the next 2 months or so.

Cheers
