### ISSUE TITLE
undefined method `contentful_instances' on running `middleman contentful`

### ISSUE THREAD

**Issue by elliotec** [contentful/contentful_middleman#133]
Just started a new middleman-blog app trying to integrate contentful_middleman. I'm using Middleman 4.2 and the `dl/upgrade-to-v4` branch as recommended in the readme. First thing i do is run `middleman contentful`, and it produces this error:

```
/Users/melliot/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/contentful_middleman-e90780f3566e/lib/contentful_middleman/commands/contentful.rb:62:in 
`contentful_instances': undefined method `contentful_instances' for #<Middleman::Application:0x70103397909540> (NoMethodError)
	from 
/Users/melliot/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/contentful_middleman-e90780f3566e/lib/contentful_middleman/commands/contentful.rb:37:in `contentful'
```

Here's my Gemfile, no other files have been touched:
``` ruby
source 'https://rubygems.org'
gem 'middleman', '~> 4.1'
gem "middleman-blog"
gem 'middleman-autoprefixer', '~> 2.7'
gem 'contentful_middleman', :git => "git://github.com/contentful/contentful_middleman.git", :branch => "dl/upgrade-to-v4"
gem 'redcarpet', '~> 3.3', '>= 3.3.3'
gem "middleman-livereload", "~> 3.1.0"
gem 'middleman-minify-html'
gem 'middleman-sprockets'
gem 'middleman-syntax'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-imageoptim', git: 'https://github.com/plasticine/middleman-imageoptim',
                            branch: 'master'
gem "builder", "~> 3.0"
```
Thanks in advance for your help!

**Comment by dlitvakb** [comment]
Hey @elliotec,

Sorry for the delay in answering.

Looks like you're missing a require statement at the beginning of your `config.rb` file. Make sure that before the `activate :contentful` statement, you have a `require 'contentful_middleman'`.

If that doesn't solve the issue, make sure to try running the command through bundler: `bundle exec middleman contentful`, this will ensure that you're running with the gems that are locked in your `Gemfile.lock` archive.

Please let me know if it helps.

Cheers
