### ISSUE TITLE
`middleman contentful` fails to create data folder

### ISSUE THREAD

**Issue by steveafrost** [contentful/contentful_middleman#135]
I'm sure I'm doing this wrong but for the life of me can't figure out where I've messed up.

config.rb

```ruby
activate :contentful do |f|
  f.access_token = ENV['CONTENTFUL_KEY']
  f.space = { site: ENV['CONTENTFUL_SPACE_ID']}
  f.rebuild_on_webhook = true
  f.content_types = {
  shows: 'shows'
 }
end
```

When I run `middleman contentful` I get no exit errors and the token & space info is correct in my env file. I do get a site-space-hash file created though no data folder w/ the actual entries from Contentful.

Has anybody else had this happen? Ideas to triage? Thank you!

**Comment by dlitvakb** [comment]
Hey @steveafrost,

Make sure that your content type ID is correct, seems like it may not be `shows`.

Cheers

**Comment by steveafrost** [comment]
Oh yup, that was it. Thanks so much for your help on this user error. :)
