### ISSUE TITLE
Does the new `links_to_entry` require updating the gem?

### ISSUE THREAD

**Issue by allanwhite** [contentful/contentful_middleman#136]
Reading the recent post on [The secret lives of entries: Using incoming links to navigate content graphs](https://www.contentful.com/blog/2018/01/16/query-content-graphs-with-incoming-links/) on the Contentful blog; would we need to update the `contentful_middleman` gem to make use of this metadata? If so, what are the plans for that happening?

If it's a separate query, adding an example to the main readme would be really helpful. I'm happy to help add it with a PR, @dlitvakb.

**Comment by dlitvakb** [comment]
Hey @allanwhite,

I've been on parental leave until today,

I'll take a look into adding this, I'll get it done most likely tomorrow.

Cheers

**Comment by dlitvakb** [comment]
Hey @allanwhite,

You can obtain this by doing `f.cda_query = {links_to_entry: 'entry_id'}`.

Same goes for `links_to_asset`.

Would you still like me to add an example?

Cheers
