### ISSUE TITLE
`bundle exec middleman contentful` just hangs - no output

### ISSUE THREAD

**Issue by mosofoco** [contentful/contentful_middleman#139]
I've tried both the v4 branch and the 4.0.0 gem on rubygems 

I'm able to connect to Contentful with the contentful gem directly.

**Comment by dlitvakb** [comment]
Hey @mosofoco,

Looks like you may be having a circular reference in your content.

You can tweak the resolution by changing the SDKs configuration using the `client_options` [option](https://github.com/contentful/contentful_middleman#configuration) and setting `max_include_resolution_depth: YOUR_INCLUDE_LEVEL + 1`, this will allow the client to quickly resolve and avoid getting stuck, as it is trying to generate a tree 20 levels deep by default, and on circular content, the tree resolution can be extremely big, as this is an exponentially complex operation.

Cheers
