### ISSUE TITLE
Difficulty accessing data

### ISSUE THREAD

**Issue by tommotaylor** [contentful/contentful_middleman#140]
I have an issue related to how `middleman_contentful` is storing my data. The crux of the problem is that the data is being stored as an Array with two entries so I have to call `data.space_key.products.first[1][:title]` rather than `data.space_key.products.first[:title]`.

My hunch is that it has to do with the fact my files are being stored in a format like `data/space_key/products/5gonrj1a2k4sYiiUCe2K00.yaml`, with the `5gonrj1a2k4sYiiUCe2K00` being the contentful entry ID of the particular product.

When I use the following:
```
<%= data.space_key.products.first[:title] %>
```

I get the error:
```
TypeError (no implicit conversion of Symbol into Integer)
```

Upon closer inspection it seems `data.space_key.products.first` is an Array with the first entry the ID of the content and the second entry the Hash with the data. Eg:

`data.space_key.products.first` =>
```
["6aoHvML5ZKmgEO2oWia0wm", #<Middleman::Util::EnhancedHash _meta=#<Middleman::Util::EnhancedHash content_type_id="products" created_at="2018-04-20T10:37:26+00:00" id="6aoHvML5ZKmgEO2oWia0wm" updated_at="2018-04-20T10:40:07+00:00"> description="The main tote bag is large — necessary for all your baby’s belongings! Its lining is divided into two parts and is detachable making it easy to wash after all kinds of spills. It has several pockets including a zip pocket for your phone, keys and more." id="6aoHvML5ZKmgEO2oWia0wm" image=#<Middleman::Util::EnhancedHash _meta=#<Middleman::Util::EnhancedHash created_at="2018-04-20T10:42:19+00:00" id="52lgLOLoVyEQKECgio8qsS" updated_at="2018-04-20T10:42:19+00:00"> description=nil title="Tote Image" url="//images.ctfassets.net/12frm5nvi038/52lgLOLoVyEQKECgio8qsS/f9bfd8da910538055e0fb499eeb8323c/bag-black.png"> image_gallery=#<Hashie::Array [#<Middleman::Util::EnhancedHash _meta=#<Middleman::Util::EnhancedHash created_at="2018-04-20T10:42:29+00:00" id="68qI1RSc2Q6I8kE8SegyA2" updated_at="2018-04-20T10:42:29+00:00"> description=nil title="Gallery Image 1" url="//images.ctfassets.net/12frm5nvi038/68qI1RSc2Q6I8kE8SegyA2/32364d78a756d75496a3b6706d5556e1/bag-white-2.jpg">, #<Middleman::Util::EnhancedHash _meta=#<Middleman::Util::EnhancedHash created_at="2018-04-20T10:42:35+00:00" id="3pUj1BWi2Agc0G2U8qoWO4" updated_at="2018-04-20T10:42:35+00:00"> description=nil title="Gallery Image 2" url="//images.ctfassets.net/12frm5nvi038/3pUj1BWi2Agc0G2U8qoWO4/fcb341d91b51a8a5045f6c6b1076db7a/bag-black-3.jpg">, #<Middleman::Util::EnhancedHash _meta=#<Middleman::Util::EnhancedHash created_at="2018-04-20T10:42:40+00:00" id="6lo0nl2adyIs2IqqU0qcgq" updated_at="2018-04-20T10:42:40+00:00"> description=nil title="Gallery Image 3" url="//images.ctfassets.net/12frm5nvi038/6lo0nl2adyIs2IqqU0qcgq/d26472227e80cc6786cfde5697059cb9/bag-white-4.jpg">]> title="Tote">]
```

So now I have to use `data.space_key.products.first[1][:title]` which seems strange to me and isn't mentioned anywhere in the docs.

My config is:
```
activate :contentful do |f|
  f.space         = { "contentful" => "XXXXXXXX" }
  f.access_token  = "XXXXXXXXXXXXX"
  f.rebuild_on_webhook = true
  f.content_types = { products: "products" }
end
```

Using `contentful_middleman (4.0.0)` on `middleman (4.2.1)`

If you could help me solve this that would be great, thanks!

**Comment by dlitvakb** [comment]
Hey @tommotaylor,

The result of `first` in this case is correct, because `products` is a hash indexed by entry ID, not an array.

You can either access your content by doing `.first[1][:title]` or iterating through the content with `.each do |_, product|`

Cheers

**Comment by tommotaylor** [comment]
@dlitvakb Thanks for the quick response. I now see in the code examples use this `|id, partner|` to access the data. 

May I suggest that a small line of copy be added that explains as you did to me, that the data when accessed "is a hash indexed by entry ID". This is different to how Middleman data usually works: https://middlemanapp.com/advanced/data-files.

Thank you for pointing this out!

**Comment by dlitvakb** [comment]
Hey @tommotaylor,

This is not different to how the middleman tutorial explains it, the issue is that you're trying to access 1 level higher than what the middleman tutorial shows.

What you're trying to do is similar to doing `data.people.first` in that example. which would return `[:friends, Array]`. Actually, it would be trying to access 2 levels higher... but the example in those docs do not offer an extra level of depth.

This is because in our integration we create a file per entry, which is called `"#{entry_id}.yaml"`, this creates a key for each file, meaning that you could do `data.contentful.your_space.your_content_type["your_entry_id"].title` for example, in this case no indexing of anything would be required, because you're accessing directly the content of the entry.
But as you're trying to iterate through a hash, you get both the key and the value of the hash per iteration, the key being the entry ID.

Hope that explains it better.

Cheers
