### ISSUE TITLE
Where are you supposed to put the mappers?

### ISSUE THREAD

**Issue by dagumak** [contentful/contentful_middleman#143]
I didn't see this in the documentation. Where do I put the mappers in the project? How does contentful_middleman know it's included?

**Comment by dlitvakb** [comment]
Hey @dagumak,

You can put them anywhere really, as long as you require them and set them on the `content_types` configuration option.

The way `contentful_middleman` is aware of your mappers is like follows:

```ruby
activate :contentful_middleman do |f|
  # ... your credentials and other configuration ...
  f.content_types = {content_type_name_you_want_to_map: {mapper: MyMapper, id: 'content_type_id'}}
end
```

Cheers

**Comment by dagumak** [comment]
@dlitvakb Thank you
