### ISSUE TITLE
Why can't I have the same content-type?

### ISSUE THREAD

**Issue by dagumak** [contentful/contentful_middleman#144]
```
activate :contentful do |f|
  f.space         = { test: 'DELETED' }
  f.access_token  = DELETED
  f.cda_query = { 
    include: 1,
    locale: '*'
  }
  f.content_types = { 
    partners: 'partners',
    partnersTestimonials: {
      id: 'partners',
      mapper: PartnerTestimonialMapper
    }
  }
end

```
I would expect this to generate a folder for partners, and a folder for partnersTestimonials, but it is only generating the one with a mapper. How can I make one directory for the data untouched and one without?

**Comment by dlitvakb** [comment]
Hey @dagumak,

Content types can only be mapped once, therefore you should either look for a way to reuse your customized content, or what the default mapper provides.

Cheers

**Comment by dagumak** [comment]
@dlitvakb  I can do the transformation on the view level, but it's dirty. It would be much cleaner to move that logic to the mapper and the views job is only to loop out all the data without any special transformations. Essentially, the mapper can allow me to map one source of data and then transform it. If I want to re-use that data and run a different mapper then I should be able to create multiple sources of data. 

Thoughts?

**Comment by dlitvakb** [comment]
Hey @dagumak,

What you can do is map the data with the default mapper, and have view helpers to manipulate the data to match what you expect.

Something like:

```ruby
# on config.rb

helpers do
  def partner_testimonial(partner)
    {
      some_field_you_want: partner.other_field,
      # ... etc ...
    }
  end
end

# on your view (i'm assuming you're using slim... but it would be similar in any other engine)
- data.contentful.spaces.your_space.partners.each do |_, partner|
  - partner_testimonial(partner).tap do |partner|
    # ... do stuff here in your view ...
```

Cheers
