### ISSUE TITLE
How do I use the same content_type source to create new data?

### ISSUE THREAD

**Issue by dagumak** [contentful/contentful_middleman#145]
For example, one of my content_types has an attribute that is an array in each entry and I want to take all the arrays and create a new directory of new yamls. For example,
```
partner 
{
   ....
   projects: [ ... ]
}
```

I want to map through each partner and create a directory of data with just projects.

**Comment by dlitvakb** [comment]
Hey @dagumak,

Each entry will create a YAML file, if you want to have other content types mapped, you need to add them to the mapped content types and ensure you're fetching those entries.

Cheers
