### ISSUE TITLE
Unclear what this error means

### ISSUE THREAD

**Issue by dagumak** [contentful/contentful_middleman#146]
Seems like there is an issue when I am using a custom mapper. I get the following error:

```
`has_multiple_locales?': undefined method `cda_query' for nil:NilClass (NoMethodError)
```

Here's my config: 
```
f.cda_query = { 
    include: 1,
    locale: '*'
  }
```

**Comment by dlitvakb** [comment]
Hey @dagumak,

Could you share your `activate :contentful` block and the definition of your custom mapper?

Cheers
