### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by javaporter** [contentful/contentful_middleman#32]
Can you add an example to the readme that illustrates

- [ ] what you would add to the config file to get MM to pull fresh contentful posts before build
- [ ] how you would create a template for blog posts (and an index that links to them, e.g. `li: a(href=post._url)= post.title`)

**Comment by renatocarvalho** [comment]
+1

**Comment by bricesanchez** [comment]
:+1:

**Comment by unity** [comment]
+1 - our precise use case is to allow blog post editing by non technical users in our organization. In that regard, 0.0.4 seemed more straightforward. Is is still doable ? Data files help but they're not well suited to blog posting imho. 

Also, do you have any examples of this used in conjunction with CI ? We have CI running right now. Do you have examples of webhooks-based deploys or something along those lines ?

**Comment by javaporter** [comment]
I was able to find an example. They link the github repo in the bottom of the article. It took a bit of time, but I was able to follow it enough to solve all my issues. I left the issue up though because I do think it's important to have this stuff in the documentation. 

I'd fork it and add it, but a lot of this is over my head, and while I can follow it, I'm not prepared to write it up.

**Comment by dlitvakb** [comment]
Hi @javaporter, @renatocarvalho, @renatocarvalho, @unity,

We've been working on adding examples on https://github.com/contentful-labs/contentful_middleman_examples

I think they cover the most usual use cases, and have a single command setup.

For the case of having pages for each resource, there is also https://github.com/contentful/contentful-middleman-pages which is a work in progress, but can currently handle the use case you're looking for.

Please let me us know if this was helpful.

We're working hard to streamline the onboarding of new developers using our product

**Comment by javaporter** [comment]
@dlitvakb Super helpful, thanks. 

The webhook is a great idea, but if people don't want to wait, Netlify currently has that and Forge either has it already or is quite close. I set up the Netlify one in like a minute (literally). 

I'll fork and add to your examples if I can. I've been using angular for stuff that doesn't need to be a dynamically created page (because it updates in seconds, vs the minutes a rebuild takes), but I'm still getting a ton of use from this repo.
