### ISSUE TITLE
Passing array in template

### ISSUE THREAD

**Issue by vladzima** [contentful/contentful_middleman#46]
Trying to figure out a way to display value from array in YAML:

```
:id: id
:title: "title"
:body: "body"
:pic:
  :title: screen
  :url: "//image.png"
```
I tried to pass an URL value in template in many ways like post["pic.url"], post["pic"]["url"] and so one, but in most cases I get NilClass error.

What would be the proper construction?

**Comment by dlitvakb** [comment]
Hi @vladzima,

Thank you for your question.

Can you please try the following way:

```ruby
post[:pic][:url]
```

As the yml you are describing is using Ruby Symbols as identifiers instead of strings.

Please let me know if that helped

**Comment by dlitvakb** [comment]
Hey @vladzima,

Have you been able to solve this problem?

**Comment by dlitvakb** [comment]
Closing as no feedback was received.
