### ISSUE TITLE
How to get assets?

### ISSUE THREAD

**Issue by sergiocerrutti** [contentful/contentful_middleman#67]
Hi,

I have added a File input to a content type, and attached an image to a new entry, but when I pull the content, the entry is created without any reference to the image, only text inputs.

How can I access to that asset from the template if it's not in the data folder?

Thank you so much, please understand I'm a completely noob using Ruby and Middleman.

**Comment by dlitvakb** [comment]
Hi @sergiocerrutti 

Hope you had a great Christmas! :christmas_tree: :santa: 

Please make sure that your Content Type is Saved and Published on the Contentful App or Contentful CMA API.

After that, you'll have something like:

```yaml
:logo:
  :title: Lemnos
  :url: "//images.contentful.com/tmdd0crcqtv5/2Y8LhXLnYAYqKCGEWG4EKI/f6a402d978eaa11d8796d27c601c163f/lemnos-logo.jpg"
```

> This example was extracted from the result of running [this command](https://github.com/contentful-labs/contentful_middleman_examples/tree/master/examples/multiple_content_types#how-to-run) on the examples repository

Once with that data in your data folder, you can use it in your templates like [this](https://github.com/contentful-labs/contentful_middleman_examples/blob/master/examples/multiple_content_types/source/index.html.erb#L50)

```erb
    <% data.catalogue.brand.each do |id, brand| %>
      <div class="row col-md-10">
        <div class="col-md-3">
          <img src="<%= brand["logo"]["url"] %>?w=140" alt="<%= brand["logo"]["title"] %>" />
        </div>
      </div>
    <% end %>
```

The Content Type used for that example is:

```json
    {
      "id": "brand",
      "name": "Brand",
      "displayField": "companyName",
      "fields": [
        {
          "id": "companyName",
          "name": "Company name",
          "type": "Text"
        },
        {
          "id": "logo",
          "name": "Logo",
          "type": "Link",
          "linkType": "Asset"
        },
        {
          "id": "companyDescription",
          "name": "Description",
          "type": "Text"
        },
        {
          "id": "website",
          "name": "Website",
          "type": "Symbol"
        },
        {
          "id": "twitter",
          "name": "Twitter",
          "type": "Symbol"
        },
        {
          "id": "email",
          "name": "Email",
          "type": "Symbol"
        },
        {
          "id": "phone",
          "name": "Phone #",
          "type": "Array",
          "items": {
            "type": "Symbol"
          }
        }
      ]
    }
```

You can find the entire Space definition for the example [here](https://github.com/contentful-labs/contentful_middleman_examples/blob/master/examples/multiple_content_types/bootstrap_templates/catalogue.json) for more details.

Please let me know if this helps

**Comment by dlitvakb** [comment]
Hi @sergiocerrutti,

We're you able to solve this with the example provided?

Cheers

**Comment by dlitvakb** [comment]
Hey @sergiocerrutti,

I'm closing this as no further response was provided.

Please feel free to re-open it if you don't find my answer satisfactory or have further related questions and we can follow up on the subject.

Cheers
