### ISSUE TITLE
Contentful middlman sets :environment instead of :mode (MM v4 issue)

### ISSUE THREAD

**Issue by jsdalton** [contentful/contentful_middleman#70]
Howdy,

For v4 support, consider the following change in MM V4:

https://middlemanapp.com/basics/upgrade-v4/#environments-and-changes-to-configure-blocks

Basically middleman now has the concepts of "environment" (e.g. development, staging, production, what have you) vs. "mode" (e.g. build or mode).

Presently Contentful Middleman behaves in the old way, by using the environment config setting to identity that the contentful task is running:

https://github.com/contentful/contentful_middleman/blob/dl/upgrade-to-v4/lib/contentful_middleman/commands/contentful.rb#L63

Presumably the behavior for V4 should be that it sets the mode to "contentful" and leaves the environment alone, so that different settings/behaviors can still be defined for environments in the new definition.

**Comment by dlitvakb** [comment]
Hey @jsdalton 

Thanks for the input,

Will add that

**Comment by dlitvakb** [comment]
Hey @jsdalton,

I've changed that now,

Feel free to keep testing the v4 integration :+1: 

Thanks again for providing feedback

**Comment by andrezimpel** [comment]
I'm seeing one problem there: What if I have a local development stage (using preview api), staging system (using preview api) and  a production system which only should show published entries. Currently there is no way to run middleman contentful and adding a stage to it, right?

Or am I missing something here?

**Comment by dlitvakb** [comment]
Hey @andrezimpel,

I've written this comment in StackOverflow about using environment variables to control development environments on middleman, please let me know if it helps.

https://stackoverflow.com/a/44928838/5439158

Cheers

**Comment by andrezimpel** [comment]
Thanks bro!
