### ISSUE TITLE
Hash dotfile created on import

### ISSUE THREAD

**Issue by tysongach** [contentful/contentful_middleman#75]
I couldn’t seem to find any information on what the `.*-hash` files that are created (placed in the project root) when importing content from Contentful. Curious what their purpose is and if they are something we would commit to Git, or rather not?

Thanks!

**Comment by dlitvakb** [comment]
Hey @tysongach,

The `.*-hash` files are created to check for cases when you have imports on a cron job.

You can use then the `ContentfulMiddleman::VersionHash` to calculate if it changed or not

Hope that helps

**Comment by tysongach** [comment]
Gotcha! So, if we choose to commit our data files of content, it wouldn’t hurt to also go ahead and commit that hash, I bet.

Thanks for the help!
