### ISSUE TITLE
How to obtain Content type id?

### ISSUE THREAD

**Issue by limay** [contentful/contentful_middleman#79]
I'm trying to setup this gem, and the only problem I have is that I don't know how to get the ID for the content type I have created in Contentful.

Ej. I can't find CONTENTTYPE_ID

f.content_types = {
    page: CONTENTTYPE_ID
 }

I tried using the API Console but I can't see the number in the json output.

Thanks

**Comment by dlitvakb** [comment]
Hey @limay,

There are 3 ways currently to fetch a Content Type ID:

1) Get it from the Content Type's JSON Preview:

* Go to https://app.contentful.com
* Select your Space and go to Content Types
* Select your Content Type
* Click on `JSON Preview`
* Find the top-level `"sys"` block in the JSON, this includes the Meta-Data of your Content Type
* The `"id"` key inside the `"sys"` block will contain your Content Type ID

2) Get it from the URI at the Contentful Editor Interface

* Go to https://app.contentful.com
* Select your Space and go to Content Types
* Select your Content Type
* Your URI should look something like: `https://app.contentful.com/spaces/<YOUR_SPACE_ID>/content_types/<YOUR_CONTENT_TYPE_ID>?...`
* Copy your Content Type ID from the section shown above

3) Get it from the API using the CDA SDK

* Install the Contentful CDA gem `gem install contentful`
* Open a Ruby Console and run the following command:

```ruby
require 'contentful'

client = Contentful::Client.new(
  space: '<YOUR_SPACE_ID>',
  access_token: '<YOUR_ACCESS_TOKEN>',
  dynamic_entries: :auto
)

client.content_types.each { |ct| puts "#{ct.name}: #{ct.id}" }
```

* That will print you the Content Type name and ID for each of your content types.

Hope this helps

Cheers

**Comment by joshkpeterson** [comment]
Found this old thread via google and it looks like some of these methods are outdated? Looking at the url and json preview, I only see the human readable name. cc @ericseandevlin

**Comment by dlitvakb** [comment]
Hey @joshkpeterson,

If you're using the latest version of `contentful_middleman`, all you're entries now have a `_meta` attribute, in which you can find your `content_type_id`.

Cheers

**Comment by nnennajohn** [comment]
@joshkpeterson , yes. It seems quite a few things have change. And after searching for a few hours, I decided to give it a go with the human readable names you mentioned. And viola! It works. I think they replaced the cryptic versions with the human readable ones. To my contentTypeId is simply "articles", "articlesCategory", etc. 

Hope this helps someone else and saves them a few hours of trying to hunt down the content type. 

For anyone here, If you happen to know how to set a "startAt" or "endAt" like you would with Firebase, please send me a holla. I would really appreciate not having to hunt again. :)

**Comment by dlitvakb** [comment]
Hey @nnennajohn,

Could you explain me what you want to accomplish a bit more? That way I could provide more insightful information.

What do you want to achieve with those fields?

Cheers

**Comment by dlitvakb** [comment]
Hey @nnennajohn,

Looks like you could do that with a `sys.updatedAt` query.

You can do it like this on `contentful_middleman`:

```ruby
activate :contentful do |f|
  # ... other config goes here ...
  f.query = { order: '-sys.updatedAt', limit: 3 }
end
```

But you seem to be needing this on a JS application, and not on `contentful_middleman` (which is this repository), so I would advise you to drop in a support request on `https://support.contentful.com`. And they'll be able to provide you with the help you need.

Cheers

**Comment by nnennajohn** [comment]
@dlitvakb Thanks so much. I really appreciate it. Will head over there now.
