### ISSUE TITLE
yaml files generated in data folder does not pick up the associated assets

### ISSUE THREAD

**Issue by samueladesoga** [contentful/contentful_middleman#88]
I have created some content in contentful and these is an image attached to each of these entries.

How ever on running contentful middleman, the data generated doesnt pick up the assets as well.

Could you please suggest how this can be fixed?

**Comment by dlitvakb** [comment]
Hey @samueladesoga,

This is an issue we're currently working actively on.

Should be soon fixed when we apply next round of patches early next week (between Monday and Tuesday).

Cheers

**Comment by samueladesoga** [comment]
I actually republished the whole content and when i did a "middleman contentful, the yaml file has now been correctly updated. I was assuming that when the assets were published. I wouldnt need to republish the content to which the asset was attached

**Comment by dlitvakb** [comment]
Hey @samueladesoga,

That's great news!

Anyway, we found the culprit of the bug and it's now being reviewed and soon to be merged and deployed.

This will be done between today and tomorrow morning.

Cheers!

PS: Closing this issue.
