### ISSUE TITLE
Only one instance actually creates files

### ISSUE THREAD

**Issue by mrh-is** [contentful/contentful_middleman#94]
I have several instances of the `contentful` extension activated in my `config.rb`, which [is allowed](https://github.com/contentful/contentful_middleman/blob/dl/upgrade-to-v4/lib/contentful_middleman/core.rb#L17), and doesn't throw an error. It seems to run ok, and prints the right amount of `create <filename>` lines in the console, but only the last instance actually creates any files.

More details that may or may not be useful:
- The outputs of the instances share ancestors within `data`, e.g., instance A puts files in `stuff/a` and instance B puts files in `stuff/b`.
- I am using the `upgrade-to-v4` branch.

**Comment by mrh-is** [comment]
This seems to have been due to my use of the same space name for all the instances. It looks like the last instance overwrites all the previous ones.

To maintain the same ancestor-sharing, I patched `VersionHash` to accept space names with slashes:
```ruby
module ContentfulMiddleman
  class VersionHash
    class << self
      def hashfilename(space_name)
        ::File.join(@source_root, ".#{space_name.gsub('/','-')}-space-hash")
      end
    end
  end
end
```

**Comment by dlitvakb** [comment]
Hey @mrh-is,

Yes, each activation requires a unique name, the serializer deletes all the contents of the folder it's serializing to on each write, therefore, two colliding spaces would overwrite each other, it's not that it's not writing on the 2nd activation, it's that the first activation gets deleted.

As for space names with slashes, space names should almost always be symbols, therefore should not have problem using it's name as is for a file name. If you have a special case, your solution should work.

Cheers
