### ISSUE TITLE
Paginating requests

### ISSUE THREAD

**Issue by juliankrispel** [contentful/contentful_middleman#96]
As far as I understand if the entry limit hits there is no warning, and the gem doesn't continue to download.

Is there a workaround? What if a user has more than 1000 entries they need to download???

**Comment by dlitvakb** [comment]
Hey @juliankrispel,

You can use the `:all_entries` option to fetch over 1000 entries. You can find more information here: https://github.com/contentful/contentful_middleman#configuration

Hope that helps

Cheers

**Comment by juliankrispel** [comment]
Hey Bruno. My question was, what if you there are more than 1000 entries???

Julian Krispel-Samsel
rainforestqa.com
goodafternoon.co

**Comment by dlitvakb** [comment]
Hey @juliankrispel, using `:all_entries` fetches over 1000 entries, as many as you have.

Cheers

**Comment by juliankrispel** [comment]
Oh cool, sry, thanks

Julian Krispel-Samsel
rainforestqa.com
goodafternoon.co

**Comment by dlitvakb** [comment]
No problem

Cheers
