### ISSUE TITLE
Subsequent references fetching only ID

### ISSUE THREAD

**Issue by martzoukos** [contentful/contentful_middleman#99]
Hello,

I'm not sure if this is a bug or a feature to reduce the size of the fetched data, but when I link to a reference from two separate fields, the information of the referenced item gets included only the first time.

Any subsequent link after that only fetches the ID.

Here's an example:

```
:available_languages:
  :de-DE:
  - :id: 53A3mvSLxSyAkuUOYwSq8Q
    :iso:
      :de-DE: es
    :description:
      :de-DE: Spanish
  - :id: 3XMaskNA128k0WaogisyG0
    :iso:
      :de-DE: de
    :description:
      :de-DE: German
:available_translations:
  :de-DE:
  - :id: 3XMaskNA128k0WaogisyG0
```

The id `3XMaskNA128k0WaogisyG0` is referenced in both the `available_languages` and `available_translations` fields but in the latter it only fetches the ID.

Thanks in advance.

**Comment by martzoukos** [comment]
Hey David, do you have any news on that?

**Comment by dlitvakb** [comment]
Hi @martzoukos,

Looks like a bug, I'll take a look into it.

Cheers

**Comment by dlitvakb** [comment]
Hey @martzoukos,

Now I'm in the office and have time to look into this, I'll start taking a look now, and let you know.

Cheers

**Comment by dlitvakb** [comment]
Hey @martzoukos,

Managed to reproduce, now checking root cause.

Cheers

**Comment by dlitvakb** [comment]
Got a fix working, adding tests around it and creating a PR.

Cheers

**Comment by martzoukos** [comment]
Apologies for my ignorance here, but how can I update my gem to get this fix?

I'm getting the 1.4.2 version but this error still persists.

Thanks!

**Comment by dlitvakb** [comment]
Hey @martzoukos,

Can you create a support request?

Please provide me in it, Space ID, Access Token, your `activate :contentful` block and the result of `bundle exec gem list`.

Maybe I missed a case in which issue appears.

Cheers

**Comment by martzoukos** [comment]
Just did.

Thank you very much!
